--LISTA TODOS OS DADOS DE UMA TABELA
SELECT * FROM CATEGORIAS

--LISTA OS DADOS DE UMA TABELA INFORMANDO QUAIS AS COLUNAS
SELECT NOME, ID FROM CATEGORIAS

--LISTA OS DADOS DE UMA TABELA FILTRANDO/WHERE PELO ID
SELECT * FROM CATEGORIAS WHERE ID = 1

--LISTA OS DADOS DE UMA TABELA ORDENANDO PELO ID
--ORDENAÇÃO POR DEFAULT É Asc
-- Asc - Crescente
-- Desc - Decrescente
SELECT * FROM CATEGORIAS ORDER BY ID Desc 

--RETORNA AS LINHAS DA TABELA CATEGORIA QUE TENHAM O ID 1 OU ID 3
SELECT * FROM CATEGORIAS WHERE ID = 1 OR ID = 3

--RETORNA AS LINHAS NA TABELA CATEGORIA QUE TENHA O ID = 3 E O NOME = DESIGN
SELECT * FROM CATEGORIAS WHERE ID = 3 AND NOME = 'DESIGN'

--LISTA TODAS AS CATEGORIAS QUE CONTENHAM 'E' NO NOME
SELECT * FROM CATEGORIAS WHERE NOME LIKE '%E%'

--LISTA TODAS AS CATEGORIAS QUE CONTENHAM 'I' NO INICIO
SELECT * FROM CATEGORIAS WHERE NOME LIKE 'I%'

--LISTA TODAS AS CATEGORIAS QUE CONTENHAM 'A' NO FINAL
SELECT * FROM CATEGORIAS WHERE NOME LIKE '%A' 

--LISTA TODAS AS CATEGORIAS QUE POSSUAM UM ID MAIOR OU IGUAL A 1
SELECT * FROM CATEGORIAS WHERE ID >= 1

--LISTA A QUANTIDADE TOTAL DOS REGISTROS DA TABELA
SELECT COUNT(*) FROM CATEGORIAS

--LISTA A QUANTIDADE DE CATEGORIAS QUE POSSUAM 'A' NO NOME 
SELECT COUNT(*) FROM CATEGORIAS WHERE NOME LIKE '%A%'  

--LISTA A QUANTIDADE DE REGISTROS INFORMADO NO TOP
SELECT TOP 2 * FROM CATEGORIAS  

--RETORNA OS REGISTROS EXISTENTES ENTRE O ID 1 E O ID 6
--BETWEEN - TRABALHA COM >= E <=
SELECT * FROM CATEGORIAS WHERE ID BETWEEN 1 AND 6

--RETORNA TODOS OS REGISTROS DA TABELA MENOS O ID 1
SELECT * FROM CATEGORIAS WHERE NOT ID = 1

--LISTA TODOS OS REGISTROS NA TABELA E APRESENTA O NOME 'LISTA DE REGISTROS'
-- AS - NÃO ALTERA O NOME DA TABELA, APENAS APRESENTA ESTE NOME NO CONSOLE
SELECT ID, NOME AS LISTA_DE_REGISTROS FROM CATEGORIAS

--LISTA TODOS OS REGISTROS NA TABELA, APRESENTA O NOME 'LISTA DE REGISTROS' E ORDENA EM ORDEM DECRESCENTE
SELECT ID, NOME AS LISTA_DE_REGISTROS FROM CATEGORIAS ORDER BY ID DESC

--RETORNA TODAS AS CATEGORIAS ONDE O ID SEJA IGUAL A 1,2,3 OU 4
SELECT * FROM CATEGORIAS WHERE ID IN(1,2,3,4)

--UPDATE - ALTERA OS DADOS DE UMA TABELA,
--SET - DEFINE 0S CAMPOS QUE DESEJO ALTERAR 'COLUNA' = 'VALOR'
--WHERE - DEFINE OS REGISTROS QUE EU DESEJO ALTERAR
UPDATE CATEGORIAS SET NOME = 'Desenvolvimento de Sistemas'
WHERE ID = 1



