
--INSERE UMA CATEGORIA INFORMANDO A COLUNA
INSERT INTO CATEGORIAS(NOME)
VALUES('DESENVOLVIMENTO');

--INSERE UMA CATEGORIA PELA ORDEM DAS COLUNAS NA TABELA
INSERT INTO CATEGORIAS
VALUES('INFORMATICA');

--INSERE VARIOS VALORES EM UM UNICO INSERT
INSERT INTO CATEGORIAS
VALUES('DESIGN'),('MARKETING')